# logging.level.org.springframework=DEBUG
# logging.level.br.com.evandrorenan.learning.web3270.session=TRACE


swagger.application.title				=Web 3270 Terminal
swagger.application.description			=Web 3270 Terminal by evandrorenan
swagger.application.license				=free
swagger.application.licenseUrl			=N/A
swagger.application.termsOfServiceUrl	=N/A
swagger.application.version				=1.0

SESSION_HOST=192.168.240.1
SESSION_HOST_PORT=51004
#  SESSION_TYPE 1 = SESSION_TYPE_3270_STR
SESSION_TYPE=1
#  codPage = 037 = Brazil
codePage=037
#  SCREEN_3D
3D=false
SESSION_WIN_STATE=false